ERROR main youe.data.scala.etl.EtlArithmeticV2 - Unsupported split Type, Only 0 :fixed num and 1 :userd efined range is available, But get 3
ERROR main youe.data.scala.etl.EtlArithmeticV2 - Unvalid split size, must be positive inter, But get -50
ERROR Executor task launch worker-0 org.apache.spark.executor.Executor - Exception in task 0.0 in stage 4.0 (TID 4)
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$12: (int) => int)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$12.apply$mcII$sp(EtlArithmeticV2.scala:1306)
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$12.apply(EtlArithmeticV2.scala:1303)
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$12.apply(EtlArithmeticV2.scala:1303)
	... 16 more
ERROR task-result-getter-0 org.apache.spark.scheduler.TaskSetManager - Task 0 in stage 4.0 failed 1 times; aborting job
ERROR Executor task launch worker-0 org.apache.spark.executor.Executor - Exception in task 0.0 in stage 4.0 (TID 4)
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$38: (int) => string)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -2147483648
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$38.apply(EtlArithmeticV2.scala:1308)
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$38.apply(EtlArithmeticV2.scala:1304)
	... 16 more
ERROR task-result-getter-0 org.apache.spark.scheduler.TaskSetManager - Task 0 in stage 4.0 failed 1 times; aborting job
ERROR Executor task launch worker-0 org.apache.spark.executor.Executor - Exception in task 0.0 in stage 4.0 (TID 4)
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$38: (int) => string)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -2147483648
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$38.apply(EtlArithmeticV2.scala:1308)
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$38.apply(EtlArithmeticV2.scala:1304)
	... 16 more
ERROR task-result-getter-0 org.apache.spark.scheduler.TaskSetManager - Task 0 in stage 4.0 failed 1 times; aborting job
ERROR Executor task launch worker-0 org.apache.spark.executor.Executor - Exception in task 0.0 in stage 4.0 (TID 4)
scala.MatchError: [ 20] (of class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema)
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$40.apply(EtlArithmeticV2.scala:1370)
	at youe.data.scala.etl.EtlArithmeticV2$$anonfun$40.apply(EtlArithmeticV2.scala:1370)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:888)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:888)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1919)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1919)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
ERROR task-result-getter-0 org.apache.spark.scheduler.TaskSetManager - Task 0 in stage 4.0 failed 1 times; aborting job
